// Generated by gencpp from file beginner_tutorials2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS2_MESSAGE_ADDTWOINTS_H
#define BEGINNER_TUTORIALS2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tutorials2/AddTwoIntsRequest.h>
#include <beginner_tutorials2/AddTwoIntsResponse.h>


namespace beginner_tutorials2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_tutorials2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials2::AddTwoInts > {
  static const char* value()
  {
    return "beginner_tutorials2/AddTwoInts";
  }

  static const char* value(const ::beginner_tutorials2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials2::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials2::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorials2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials2::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials2::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_tutorials2::AddTwoInts > 
template<>
struct DataType< ::beginner_tutorials2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials2::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials2::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials2::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorials2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials2::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials2::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_tutorials2::AddTwoInts > 
template<>
struct DataType< ::beginner_tutorials2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials2::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorials2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS2_MESSAGE_ADDTWOINTS_H
